version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_DB: ev_charging
      POSTGRES_USER: ev_user
      POSTGRES_PASSWORD: ev_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      retries: 5

  app:
    build: .
    command: pnpm run run:server
    environment:
      DATABASE_SOURCE: postgres://ev_user:ev_pass@db:5432/ev_charging
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data:
